/* File Automatically Generated by LSC. Please do not edit manually. */
export const generatedMenuItems = [
  {
    id: 'polus-notebooks-hub',
    route: 'polus-notebooks-hub',
    click: 'tenant-switch',
    text: 'PolusNotebooksHub',
    icon: 'icon-lsi-info-fill'
  }
];
