/* File Automatically Generated by LSC. Please do not edit manually. */

import {Routes} from '@angular/router';

export const generatedRoutes: Routes = [
  {
    path: 'polus-notebooks-hub',
    loadChildren: () => import('@labshare/polus-notebooks-hub').then(m => m.PolusNotebooksHubModule)
  }
];
